name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=leydigaba_app.py-pruebas
            -Dsonar.organization=leydigaba
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
